### ISSUE TITLE
Angular is not defined error

### ISSUE THREAD

**Issue by Rajan** [hoxton-one/ds-demo-simple-app-ng#1]
bower install       angular#1.3.20

deepstream.io-client-js#0.3.6 bower_components/deepstream.io-client-js

angular#1.3.20 bower_components/angular
Rajans-MacBook-Pro:ds-demo-simple-app-ng rajanchandi$ sudo node src/start-ng.js 
/Users/rajanchandi/WebstormProjects/ds-demo-simple-app-ng/src/start-ng.js:4
angular
^

ReferenceError: angular is not defined
    at Object.<anonymous> (/Users/rajanchandi/WebstormProjects/ds-demo-simple-app-ng/src/start-ng.js:4:1)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3

**Comment by WolframHempel** [comment]
Sorry, that's a browser app in angular :-). Don't run ` sudo node src/start-ng.js`, just open index.html in your browser (or a couple of browser windows) with deepstream running on port 6020

**Comment by Rajan** [comment]
Angular-less normal example works for me now. Had to change from bower path to node_modules though to make it work.
